title : esm-bb for buildbot
git-repository: https://github.com/slcs-jsc/mptrac.git
builder-name: MPTRAC_ESMBB
worker: ESM_JUWELS
project: MPTRAC
scheduler: 
  - FORCE
  - CHANGE
branch: 
  - esm-buildbot
poll-interval: 3000
time-out: 3600
steps:
  - name: build mptrac
    cmd: sh config/build_cpu.sh
    env:
    work_dir:
  - name: test mptrac
    cmd: sh config/test_cpu.sh
    env:
    work_dir:
