title : esm-bb for buildbot
git-repository: https://github.com/slcs-jsc/mptrac.git
builder: MPTRAC_ESMBB
worker: ESM_JUWELS
project: MPTRAC
scheduler: 
  - FORCE
  - CHANGE
branch: 
  - master
poll-interval: 3600
time-out: 3600
steps:
  - name: move files
    cmd: cp config/build.sh ../. 
    env:
    work_dir: 
  - name: build mptrac
    cmd: sh build.sh
    env:
    work_dir:
