title : esm-bb for buildbot
git-repository: https://github.com/slcs-jsc/mptrac.git
builder: MPTRAC_ESMBB
worker: ESM_JUWELS
project: MPTRAC
scheduler: 
  - FORCE
  - CHANGE
branch: 
  - master
poll-interval: 3600
time-out: 3600
steps:
  - name: remove the external setup files 
    cmd: rm -fr builder
    env:
    work_dir: build 
  - name: clone the setup files
    cmd: git sparse-checkout init --cone
    env:
    work_dir: build
  - name: git sparse-checkout init
    cmd: git sparse-checkout set BUILDER_MPTRAC_CPU
    env:
    work_dir: build/builder
  - name: git sparse-checkout folder
    cmd: git sparse-checkout set BUILDER_MPTRAC_CPU
    env:
    work_dir: build/builder
  - name: git sparse-checkout the files
    cmd: git checkout @
    env:
    work_dir: build/builder
  - name: move files
    cmd: mv BUILDER_MPTRAC_CPU/{prebuild,build.sh,test.sh} ../. 
    env:
    work_dir: build/builder
  - name: pre-build for the external libraries"
    cmd:  sh prebuild.sh 
    env:  
    work_dir: build
  - name: build mptrac
    cmd: sh build.sh
    env:
    work_dir:
  - name: test mptrac
    cmd: sh test.sh
    env:
    work_dir:
