#! /bin/bash

#DIR=$PWD
module use $OTHERSTAGES 
module load Stages/Devel-2019a
module load PGI/19.10-GCC-8.3.0
module load ParaStationMPI/5.4.2-1-CUDA

#git clone  https://github.com/Kaveh01/mptrac.git
#cd mptrac/lib
        ./build.sh
   cd ../src
	sed -i 's/#MPI/ MPI/' Makefile
	sed -i 's/#GPU/ GPU/' Makefile
	sed -i 's/STATIC =/#STATIC =/' Makefile
        make -j8
#echo "Please add" $DIR/mptrac/lib/build/lib/ "to your LD_LIBRARY_PATH." 
