// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// 
// Parameter Header File
// 
// Generated by KPP-3.0.0 symbolic chemistry Kinetics PreProcessor
//       (https:/github.com/KineticPreProcessor/KPP
// KPP is distributed under GPL, the general public licence
//       (http://www.gnu.org/copyleft/gpl.html)
// (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
// (C) 1997-2022, A. Sandu, Michigan Tech, Virginia Tech
//     With important contributions from:
//        M. Damian,   Villanova University, Philadelphia, PA, USA
//        R. Sander,   Max-Planck Institute for Chemistry, Mainz, Germany
//        M. Long,     Renaissance Fiber, LLC, North Carolina, USA
//        H. Lin,      Harvard University, Cambridge, MA, USA
//        R. Yantosca, Harvard University, Cambridge, MA, USA
// 
// File                 : chem_Parameters.h
// Equation file        : chem.kpp
// Output root filename : chem
// 
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~




#define NSPEC                13          /* Number of chemical species */
#define NVAR                 10          /* Number of Variable species */
#define NFAM                 1           /* Number of Prod/Loss Families */
#define NVARACT              10          /* Number of Active species */
#define NFIX                 3           /* Number of Fixed species */
#define NREACT               27          /* Number of reactions */
#define NVARST               0           /* Starting of variables in conc. vect. */
#define NFIXST               10          /* Starting of fixed in conc. vect. */
#define NONZERO              44          /* Number of nonzero entries in Jacobian */
#define LU_NONZERO           45          /* Number of nonzero entries in LU factoriz. of Jacobian */
#define CNVAR                11          /* (NVAR+1) Number of elements in compressed row format */
#define NLOOKAT              1           /* Number of species to look at */
#define NMONITOR             1           /* Number of species to monitor */
#define NMASS                1           /* Number of atoms to check mass balance */

// Index declaration for variable species in C and VAR
//   VAR(ind_spc) = C(ind_spc)

#define ind_n2o              0          
#define ind_ccl3f            1          
#define ind_ccl2f2           2          
#define ind_cclf3            3          
#define ind_o1d              4          
#define ind_o3               5          
#define ind_o3p              6          
#define ind_h2o2             7          
#define ind_oh               8          
#define ind_ho2              9          

// Index declaration for fixed species in C
//   C(ind_spc)

#define ind_o2               10         
#define ind_n2               11         
#define ind_h2o              12         

// Index declaration for fixed species in FIX
//    FIX(indf_spc) = C(ind_spc) = C(NVAR+indf_spc)

#define indf_o2              0          
#define indf_n2              1          
#define indf_h2o             2          
