// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// 
// Auxiliary Routines File
// 
// Generated by KPP-3.0.0 symbolic chemistry Kinetics PreProcessor
//       (https:/github.com/KineticPreProcessor/KPP
// KPP is distributed under GPL, the general public licence
//       (http://www.gnu.org/copyleft/gpl.html)
// (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
// (C) 1997-2022, A. Sandu, Michigan Tech, Virginia Tech
//     With important contributions from:
//        M. Damian,   Villanova University, Philadelphia, PA, USA
//        R. Sander,   Max-Planck Institute for Chemistry, Mainz, Germany
//        M. Long,     Renaissance Fiber, LLC, North Carolina, USA
//        H. Lin,      Harvard University, Cambridge, MA, USA
//        R. Yantosca, Harvard University, Cambridge, MA, USA
// 
// File                 : chem_Util.c
// Equation file        : chem.kpp
// Output root filename : chem
// 
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include "chem_Parameters.h"
#include "chem_Global.h"
#include "chem_Sparse.h"



// User INLINED Utility Functions


#include "libtrac.h"

void kppchem_output2atm(
	atm_t * atm,
	ctl_t * ctl, 
	int ip){
	
		/*Output to air parcel.. */

		VAR2atm(ind_o3p, ctl->qnt_Co3p)
		VAR2atm(ind_o1d, ctl->qnt_Co1d)
		VAR2atm(ind_h2o2, ctl->qnt_Ch2o2)
		VAR2atm(ind_oh, ctl->qnt_Coh)
		VAR2atm(ind_ho2, ctl->qnt_Cho2)
		VAR2atm(ind_o3, ctl->qnt_Co3)
		VAR2atm(ind_n2o, ctl->qnt_Cn2o)
		VAR2atm(ind_ccl3f, ctl->qnt_Cccl3f)
		VAR2atm(ind_ccl2f2, ctl->qnt_Cccl2f2)
		VAR2atm(ind_cclf3, ctl->qnt_Ccclf3)
		//VAR2atm(ind_co, ctl->qnt_Cco)
}

void kppchem_init_cqnt_clim(
	ctl_t * ctl,
	atm_t * atm,
	clim_t * clim,
	int ip){	
		atm->q[ctl->qnt_Cho2][ip] = 			
			clim_var(clim, atm->time[ip], atm->lat[ip], atm->p[ip], clim->ho2);
		atm->q[ctl->qnt_Co1d][ip] = 			
			clim_var(clim, atm->time[ip], atm->lat[ip], atm->p[ip], clim->o1d);
		atm->q[ctl->qnt_Coh][ip] = 			
			clim_var(clim, atm->time[ip], atm->lat[ip], atm->p[ip], clim->oh);

}

void kppchem_init_cqnt_met(
ctl_t * ctl,
atm_t * atm,
met_t * met0,
met_t * met1,
int ip){
	INTPOL_INIT;
	double o3;
  INTPOL_3D(o3,1)
	atm->q[ctl->qnt_Co3][ip] = o3;
	
}

void interparc_mixing(
	ctl_t * ctl,
	atm_t * atm,
	clim_t * clim,
	int *ixs,
	int *iys,	
	int *izs){

	interparc_mixing_help(ctl, atm, clim, ixs, iys, izs, ctl->qnt_Co3p);
	interparc_mixing_help(ctl, atm, clim, ixs, iys, izs, ctl->qnt_Co1d);
	interparc_mixing_help(ctl, atm, clim, ixs, iys, izs, ctl->qnt_Ch2o2);
	interparc_mixing_help(ctl, atm, clim, ixs, iys, izs, ctl->qnt_Coh);
	interparc_mixing_help(ctl, atm, clim, ixs, iys, izs, ctl->qnt_Cho2);
	interparc_mixing_help(ctl, atm, clim, ixs, iys, izs, ctl->qnt_Ch);
	interparc_mixing_help(ctl, atm, clim, ixs, iys, izs, ctl->qnt_Co3);
	interparc_mixing_help(ctl, atm, clim, ixs, iys, izs, ctl->qnt_Cn2o);
	interparc_mixing_help(ctl, atm, clim, ixs, iys, izs, ctl->qnt_Cccl3f);
	interparc_mixing_help(ctl, atm, clim, ixs, iys, izs, ctl->qnt_Cccl2f2);
	interparc_mixing_help(ctl, atm, clim, ixs, iys, izs, ctl->qnt_Ccclf3);	
	interparc_mixing_help(ctl, atm, clim, ixs, iys, izs, ctl->qnt_Cco);		
}

void kppchem_bound_cond(
	ctl_t * ctl,
	atm_t * atm,
	int ip){
	if (ctl->qnt_Cccl3f>=0)
			atm->q[ctl->qnt_Cccl3f][ip] = 1e7;
	if (ctl->qnt_Cco>=0)
			atm->q[ctl->qnt_Cco][ip] = 1e7;
}


// End INLINED Utility Functions

// Utility Functions from KPP_HOME/util/util
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// 
// UTIL - Utility functions
//   Arguments :
// 
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

/*
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
*/
double min( double x, double y )
{
  return ( x <= y ) ? x : y;
}

double max( double x, double y )
{
  return ( x >= y ) ? x : y;
}

static FILE *fpDat = 0;

int InitSaveData()
{
  fpDat = fopen("chem.dat", "w");
  if( fpDat == 0 ) {
    printf("\n Can't create file : chem.dat");
    exit(1);
  }
  return 0;
}

int SaveData()
{
int i;

  fprintf( fpDat, "%6.1f ", TIME/3600.0 );
  for( i = 0; i < NLOOKAT; i++ )
    fprintf( fpDat, "%24.16e ", C[ LOOKAT[i] ]/CFACTOR );
  fprintf( fpDat, "\n");
  return 0;
}

int CloseSaveData()
{
  fclose( fpDat );
  return 0;
}

int GenerateMatlab( char * prefix )
{
int i;
FILE *fpMatlab;
  
  fpMatlab = fopen("chem.m", "w");
  if( fpMatlab == 0 ) {
    printf("\n Can't create file : chem.m");
    exit(1);
  }

  fprintf(fpMatlab, "load chem.dat;\n");
  fprintf(fpMatlab, "%sc = chem;\n", prefix);
  fprintf(fpMatlab, "clear chem;\n");
  fprintf(fpMatlab, "%st=%sc(:,1);\n", prefix, prefix);
  fprintf(fpMatlab, "%sc(:,1)=[];\n", prefix);
  
  for( i = 0; i < NLOOKAT; i++ )
    fprintf( fpMatlab, "%s%s = %sc(:,%d);\n", 
            prefix, SPC_NAMES[LOOKAT[i]], 
            prefix, i+1 );
  
  fclose( fpMatlab );
  return 0;
}

// End Utility Functions from KPP_HOME/util/util
// End of UTIL function
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// 
// Shuffle_user2kpp - function to copy concentrations from USER to KPP
//   Arguments :
//      V_USER    - Concentration of variable species in USER's order
//      V         - Concentrations of variable species (local)
// 
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

void Shuffle_user2kpp( 
  double V_USER[NVAR],                   /* Concentration of variable species in USER's order */
  double V[NVAR]                         /* Concentrations of variable species (local) */
)
{
  V[6] = V_USER[0];
  V[4] = V_USER[1];
  V[8] = V_USER[3];
  V[9] = V_USER[4];
  V[7] = V_USER[5];
  V[5] = V_USER[6];
  V[0] = V_USER[7];
  V[1] = V_USER[8];
  V[2] = V_USER[9];
}

// End of Shuffle_user2kpp function
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// 
// Shuffle_kpp2user - function to restore concentrations from KPP to USER
//   Arguments :
//      V         - Concentrations of variable species (local)
//      V_USER    - Concentration of variable species in USER's order
// 
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

void Shuffle_kpp2user( 
  double V[NVAR],                        /* Concentrations of variable species (local) */
  double V_USER[NVAR]                    /* Concentration of variable species in USER's order */
)
{
  V_USER[0] = V[6];
  V_USER[1] = V[4];
  V_USER[3] = V[8];
  V_USER[4] = V[9];
  V_USER[5] = V[7];
  V_USER[6] = V[5];
  V_USER[7] = V[0];
  V_USER[8] = V[1];
  V_USER[9] = V[2];
}

// End of Shuffle_kpp2user function
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// 
// GetMass - compute total mass of selected atoms
//   Arguments :
//      CL        - Concentration of all species (local)
//      Mass      - value of mass balance
// 
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

void GetMass( 
  double CL[NSPEC],                      /* Concentration of all species (local) */
  double Mass[1]                         /* value of mass balance */
)
{
}

// End of GetMass function
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


