// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// 
// Sparse Stoichiometric Data Structures File
// 
// Generated by KPP-3.0.0 symbolic chemistry Kinetics PreProcessor
//       (https:/github.com/KineticPreProcessor/KPP
// KPP is distributed under GPL, the general public licence
//       (http://www.gnu.org/copyleft/gpl.html)
// (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
// (C) 1997-2022, A. Sandu, Michigan Tech, Virginia Tech
//     With important contributions from:
//        M. Damian,   Villanova University, Philadelphia, PA, USA
//        R. Sander,   Max-Planck Institute for Chemistry, Mainz, Germany
//        M. Long,     Renaissance Fiber, LLC, North Carolina, USA
//        H. Lin,      Harvard University, Cambridge, MA, USA
//        R. Yantosca, Harvard University, Cambridge, MA, USA
// 
// File                 : chem_StoichiomSP.c
// Equation file        : chem.kpp
// Output root filename : chem
// 
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include "chem_Parameters.h"
#include "chem_Global.h"
#include "chem_Sparse.h"



// Row-compressed sparse data for the Jacobian of reaction products JVRP
 /* Beginning of rows in JVRP */

  int  CROW_JVRP[] = {
       0,  2,  3,  3 }; 

 /* Column indices in JVRP */

  int  ICOL_JVRP[] = {
       1,  2,  2 }; 

 /* Row indices in JVRP */

  int  IROW_JVRP[] = {
       0,  0,  1 }; 




//  Stoichiometric Matrix in Compressed Column Sparse Format

 /* Beginning of columns in STOICM */

  int  CCOL_STOICM[] = {
       0,  3,  5,  6 }; 

 /* Row indices in STOICM */

  int  IROW_STOICM[] = {
       0,  1,  2,  0,  2,  1 }; 

 /* Column indices in STOICM */

  int  ICOL_STOICM[] = {
       0,  0,  0,  1,  1,  2 }; 

 /* Stoichiometric Matrix in compressed column format */

  double  STOICM[] = {
         1,   -1,   -1,    1,   -1,    1 }; 


