// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// 
// The Stoichiometric Chemical Model File
// 
// Generated by KPP-3.0.0 symbolic chemistry Kinetics PreProcessor
//       (https:/github.com/KineticPreProcessor/KPP
// KPP is distributed under GPL, the general public licence
//       (http://www.gnu.org/copyleft/gpl.html)
// (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
// (C) 1997-2022, A. Sandu, Michigan Tech, Virginia Tech
//     With important contributions from:
//        M. Damian,   Villanova University, Philadelphia, PA, USA
//        R. Sander,   Max-Planck Institute for Chemistry, Mainz, Germany
//        M. Long,     Renaissance Fiber, LLC, North Carolina, USA
//        H. Lin,      Harvard University, Cambridge, MA, USA
//        R. Yantosca, Harvard University, Cambridge, MA, USA
// 
// File                 : chem_Stoichiom.c
// Equation file        : chem.kpp
// Output root filename : chem
// 
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include "chem_Parameters.h"
#include "chem_Global.h"
#include "chem_Sparse.h"


// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// 
// ReactantProd - Reactant Products in each equation
//   Arguments :
//      V         - Concentrations of variable species (local)
//      F         - Concentrations of fixed species (local)
//      ARP       - Reactant product in each equation
// 
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

void ReactantProd( 
  double V[NVAR],                        /* Concentrations of variable species (local) */
  double F[NFIX],                        /* Concentrations of fixed species (local) */
  double ARP[NREACT]                     /* Reactant product in each equation */
)
{

// Reactant Products in each equation are useful in the
//     stoichiometric formulation of mass action law
  ARP[0] = V[1]*V[2];
  ARP[1] = V[2]*F[0];
  ARP[2] = F[1]*F[1];
}

// End of ReactantProd function
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// 
// JacReactantProd - Jacobian of Reactant Products vector
//   Arguments :
//      V         - Concentrations of variable species (local)
//      F         - Concentrations of fixed species (local)
//      JVRP      - d ARP(1:NREACT)/d VAR (1:NVAR)
// 
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

void JacReactantProd( 
  double V[NVAR],                        /* Concentrations of variable species (local) */
  double F[NFIX],                        /* Concentrations of fixed species (local) */
  double JVRP[NJVRP]                     /* d ARP(1:NREACT)/d VAR (1:NVAR) */
)
{

// Reactant Products in each equation are useful in the
//    stoichiometric formulation of mass action law
// Below we compute the Jacobian of the Reactant Products vector
//    w.r.t. variable species: d ARP(1:NREACT) / d Var(1:NVAR)

// JVRP(0) = dARP(0)/dV(1)
  JVRP[0] = V[2];
// JVRP(1) = dARP(0)/dV(2)
  JVRP[1] = V[1];
// JVRP(2) = dARP(1)/dV(2)
  JVRP[2] = F[0];
}

// End of JacReactantProd function
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



// Begin Derivative w.r.t. Rate Coefficients


// End Derivative w.r.t. Rate Coefficients


// Begin Jacobian Derivative w.r.t. Rate Coefficients


// End Jacobian Derivative w.r.t. Rate Coefficients

