// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// 
// Parameter Header File
// 
// Generated by KPP-3.0.0 symbolic chemistry Kinetics PreProcessor
//       (https:/github.com/KineticPreProcessor/KPP
// KPP is distributed under GPL, the general public licence
//       (http://www.gnu.org/copyleft/gpl.html)
// (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
// (C) 1997-2022, A. Sandu, Michigan Tech, Virginia Tech
//     With important contributions from:
//        M. Damian,   Villanova University, Philadelphia, PA, USA
//        R. Sander,   Max-Planck Institute for Chemistry, Mainz, Germany
//        M. Long,     Renaissance Fiber, LLC, North Carolina, USA
//        H. Lin,      Harvard University, Cambridge, MA, USA
//        R. Yantosca, Harvard University, Cambridge, MA, USA
// 
// File                 : chem_Parameters.h
// Equation file        : chem.kpp
// Output root filename : chem
// 
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~




#define NSPEC                5           /* Number of chemical species */
#define NVAR                 3           /* Number of Variable species */
#define NFAM                 1           /* Number of Prod/Loss Families */
#define NVARACT              2           /* Number of Active species */
#define NFIX                 2           /* Number of Fixed species */
#define NREACT               3           /* Number of reactions */
#define NVARST               0           /* Starting of variables in conc. vect. */
#define NFIXST               3           /* Starting of fixed in conc. vect. */
#define NONZERO              7           /* Number of nonzero entries in Jacobian */
#define LU_NONZERO           7           /* Number of nonzero entries in LU factoriz. of Jacobian */
#define CNVAR                4           /* (NVAR+1) Number of elements in compressed row format */
#define NLOOKAT              1           /* Number of species to look at */
#define NMONITOR             1           /* Number of species to monitor */
#define NMASS                1           /* Number of atoms to check mass balance */

// Index declaration for variable species in C and VAR
//   VAR(ind_spc) = C(ind_spc)

#define ind_SO4              0          
#define ind_H2O2             1          
#define ind_SO2              2          

// Index declaration for fixed species in C
//   C(ind_spc)

#define ind_OH               3          
#define ind_HO2              4          

// Index declaration for fixed species in FIX
//    FIX(indf_spc) = C(ind_spc) = C(NVAR+indf_spc)

#define indf_OH              0          
#define indf_HO2             1          
