on:
  push:
    branches: 
      - master

jobs:

  deploying_mkdoc:
    runs-on: ubuntu-latest
    steps:
      - name: mkdocs
        uses: actions/checkout@v3
      - name: preparing_environment
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: installing_mkdocs
        run: pip install mkdocs ; pip install mkdocs-material; 
             cd docs ; mkdocs gh-deploy --force --clean --verbose
        
  deploying_doxygen:
    runs-on: ubuntu-latest
    needs: deploying_mkdoc
    steps:
      - name: doxygen
        uses: actions/checkout@v3
      - name: debugging
        run: echo `pwd`; echo `ls docs` ; echo `ls docs/*`
      - name: preparing_doxygen
        uses: mattnotmitt/doxygen-action@v1.9.4
        with:
            doxyfile-path: 'Doxyfile'
            working-directory: 'docs'
      - name: debugging_2
        run: echo `pwd`; echo `ls docs` ; echo `ls docs/*`
      - name: deploy_doxygen
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./docs/docs/html
            destination_dir: doxygen

