name: docs

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-24.04

    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: preparing_environment
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: installing_mkdocs
        run: pip install mkdocs mkdocs-material

      - name: building_mkdocs
        run: cd docs && mkdocs build --clean --verbose

      - name: preparing_doxygen
        uses: mattnotmitt/doxygen-action@v1.9.4
        with:
          doxyfile-path: Doxyfile
          working-directory: docs

      - name: Merge Doxygen output into site
        run: |
          mkdir -p docs/site/doxygen
          cp -r docs/docs/html/. docs/site/doxygen/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/site
