// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// 
// The ODE Function of Chemical Model File
// 
// Generated by KPP-3.0.0 symbolic chemistry Kinetics PreProcessor
//       (https:/github.com/KineticPreProcessor/KPP
// KPP is distributed under GPL, the general public licence
//       (http://www.gnu.org/copyleft/gpl.html)
// (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
// (C) 1997-2022, A. Sandu, Michigan Tech, Virginia Tech
//     With important contributions from:
//        M. Damian,   Villanova University, Philadelphia, PA, USA
//        R. Sander,   Max-Planck Institute for Chemistry, Mainz, Germany
//        M. Long,     Renaissance Fiber, LLC, North Carolina, USA
//        H. Lin,      Harvard University, Cambridge, MA, USA
//        R. Yantosca, Harvard University, Cambridge, MA, USA
// 
// File                 : chem_Function.c
// Equation file        : chem.kpp
// Output root filename : chem
// 
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include "chem_Parameters.h"
#include "chem_Global.h"
#include "chem_Sparse.h"


// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// 
// Fun - time derivatives of variables - Aggregate form
//   Arguments :
//      V         - Concentrations of variable species (local)
//      F         - Concentrations of fixed species (local)
//      RCT       - Rate constants (local)
//      Vdot      - Time derivative of variable species concentrations
//      Aout      - Optional argument to return equation rate constants
// 
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

void Fun( 
  double V[NVAR],                        /* Concentrations of variable species (local) */
  double F[NFIX],                        /* Concentrations of fixed species (local) */
  double RCT[NREACT],                    /* Rate constants (local) */
  double Vdot[NVAR],                     /* Time derivative of variable species concentrations */
  double Aout[NREACT]                    /* Optional argument to return equation rate constants */
)
{

// Local variables
double A[NREACT];                        /* Rate for each equation */

// Computation of equation rates
  A[0] = RCT[0]*V[6]*F[0];
  A[1] = RCT[1]*V[5]*V[6];
  A[2] = RCT[2]*V[4]*F[0];
  A[3] = RCT[3]*V[4]*V[5];
  A[4] = RCT[4]*V[4]*F[2];
  A[5] = RCT[5]*V[4]*F[1];
  A[6] = RCT[6]*V[4]*F[1];
  A[7] = RCT[7]*V[0]*V[4];
  A[8] = RCT[8]*V[1]*V[4];
  A[9] = RCT[9]*V[2]*V[4];
  A[10] = RCT[10]*V[3]*V[4];
  A[11] = RCT[11]*V[6]*V[9];
  A[12] = RCT[12]*V[6]*V[7];
  A[13] = RCT[13]*V[5]*V[8];
  A[14] = RCT[14]*V[8]*V[8];
  A[15] = RCT[15]*V[8]*V[8];
  A[16] = RCT[16]*V[8]*V[9];
  A[17] = RCT[17]*V[7]*V[8];
  A[18] = RCT[18]*V[5]*V[9];
  A[19] = RCT[19]*V[9]*V[9];
  A[20] = RCT[20]*F[0];
  A[21] = RCT[21]*V[5];
  A[22] = RCT[22]*V[5];
  A[23] = RCT[23]*V[9];
  A[24] = RCT[24]*V[7];
  A[25] = RCT[25]*V[0];
  A[26] = RCT[26]*V[1];
  A[27] = RCT[27]*V[2];


// Aggregate function
  Vdot[0] = A[6]-A[7]-A[25];
  Vdot[1] = -0.9*A[8]-A[26];
  Vdot[2] = -0.86*A[9]-A[27];
  Vdot[3] = -0.82*A[10];
  Vdot[4] = -A[2]-A[3]-A[4]-A[5]-A[6]-A[7]-A[8]-A[9]-A[10]+A[21]+A[24]
           +A[25];
  Vdot[5] = A[0]-A[1]-A[3]-A[13]-A[18]-A[21]-A[22];
  Vdot[6] = -A[0]-A[1]+A[2]+A[3]+A[5]+0.1*A[8]+0.14*A[9]+0.18*A[10]
           -A[11]-A[12]+A[14]+2*A[20]+A[22]+A[23];
  Vdot[7] = -A[12]+A[15]-A[17]+A[19]-A[24];
  Vdot[8] = 2*A[4]+A[11]+A[12]-A[13]-2*A[14]-2*A[15]-A[16]-A[17]+A[18]
           +A[23]+A[24];
  Vdot[9] = -A[11]+A[12]+A[13]-A[16]+A[17]-A[18]-2*A[19]-A[23];
}

// End of Fun function
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// 
// Fun_SPLIT - time derivatives of variables - Split form
//   Arguments :
//      V         - Concentrations of variable species (local)
//      F         - Concentrations of fixed species (local)
//      RCT       - Rate constants (local)
//      Vdot      - Time derivative of variable species concentrations
//      P_VAR     - Production term
//      D_VAR     - Destruction term
//      Aout      - Optional argument to return equation rate constants
// 
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

void Fun_SPLIT( 
  double V[NVAR],                        /* Concentrations of variable species (local) */
  double F[NFIX],                        /* Concentrations of fixed species (local) */
  double RCT[NREACT],                    /* Rate constants (local) */
  double Vdot[NVAR],                     /* Time derivative of variable species concentrations */
  double P_VAR[NVAR],                    /* Production term */
  double D_VAR[NVAR],                    /* Destruction term */
  double Aout[NREACT]                    /* Optional argument to return equation rate constants */
)
{

// Local variables
double A[NREACT];                        /* Rate for each equation */

// Computation of equation rates
  A[0] = RCT[0]*V[6]*F[0];
  A[2] = RCT[2]*V[4]*F[0];
  A[3] = RCT[3]*V[4]*V[5];
  A[4] = RCT[4]*V[4]*F[2];
  A[5] = RCT[5]*V[4]*F[1];
  A[6] = RCT[6]*V[4]*F[1];
  A[8] = RCT[8]*V[1]*V[4];
  A[9] = RCT[9]*V[2]*V[4];
  A[10] = RCT[10]*V[3]*V[4];
  A[11] = RCT[11]*V[6]*V[9];
  A[12] = RCT[12]*V[6]*V[7];
  A[13] = RCT[13]*V[5]*V[8];
  A[14] = RCT[14]*V[8]*V[8];
  A[15] = RCT[15]*V[8]*V[8];
  A[17] = RCT[17]*V[7]*V[8];
  A[18] = RCT[18]*V[5]*V[9];
  A[19] = RCT[19]*V[9]*V[9];
  A[20] = RCT[20]*F[0];
  A[21] = RCT[21]*V[5];
  A[22] = RCT[22]*V[5];
  A[23] = RCT[23]*V[9];
  A[24] = RCT[24]*V[7];
  A[25] = RCT[25]*V[0];


// Production function
  P_VAR[0] = A[6];
  P_VAR[1] = 0.1*A[8];
  P_VAR[2] = 0.14*A[9];
  P_VAR[3] = 0.18*A[10];
  P_VAR[4] = A[21]+A[24]+A[25];
  P_VAR[5] = A[0];
  P_VAR[6] = A[2]+A[3]+A[5]+0.1*A[8]+0.14*A[9]+0.18*A[10]+A[14]+2*A[20]
            +A[22]+A[23];
  P_VAR[7] = A[15]+A[19];
  P_VAR[8] = 2*A[4]+A[11]+A[12]+A[18]+A[23]+A[24];
  P_VAR[9] = A[12]+A[13]+A[17];

// Destruction function
  D_VAR[0] = RCT[7]*V[4]+RCT[25];
  D_VAR[1] = RCT[8]*V[4]+RCT[26];
  D_VAR[2] = RCT[9]*V[4]+RCT[27];
  D_VAR[3] = RCT[10]*V[4];
  D_VAR[4] = RCT[2]*F[0]+RCT[3]*V[5]+RCT[4]*F[2]+RCT[5]*F[1]+RCT[6]
            *F[1]+RCT[7]*V[0]+RCT[8]*V[1]+RCT[9]*V[2]+RCT[10]*V[3];
  D_VAR[5] = RCT[1]*V[6]+RCT[3]*V[4]+RCT[13]*V[8]+RCT[18]*V[9]+RCT[21]
            +RCT[22];
  D_VAR[6] = RCT[0]*F[0]+RCT[1]*V[5]+RCT[11]*V[9]+RCT[12]*V[7];
  D_VAR[7] = RCT[12]*V[6]+RCT[17]*V[8]+RCT[24];
  D_VAR[8] = RCT[13]*V[5]+RCT[14]*2*V[8]+RCT[15]*2*V[8]+RCT[16]*V[9]
            +RCT[17]*V[7];
  D_VAR[9] = RCT[11]*V[6]+RCT[16]*V[8]+RCT[18]*V[5]+RCT[19]*2*V[9]
            +RCT[23];

  for( int n=0; n<NVAR; n++ ) {
    Vdot[n] = P_VAR[n] - D_VAR[n]*V[n];
  }
}

// End of Fun_SPLIT function
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// 
// CalcStoichNum - calculate stoichiometric numbers
//   Arguments :
//      StoichNum - Stoichiometric numbers
// 
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

void CalcStoichNum( 
  double StoichNum[NVAR][NREACT]         /* Stoichiometric numbers */
)
{
  StoichNum[0][6] = 1;
  StoichNum[0][7] = -1;
  StoichNum[0][25] = -1;
  StoichNum[1][8] = -0.9;
  StoichNum[1][26] = -1;
  StoichNum[2][9] = -0.86;
  StoichNum[2][27] = -1;
  StoichNum[3][10] = -0.82;
  StoichNum[4][2] = -1;
  StoichNum[4][3] = -1;
  StoichNum[4][4] = -1;
  StoichNum[4][5] = -1;
  StoichNum[4][6] = -1;
  StoichNum[4][7] = -1;
  StoichNum[4][8] = -1;
  StoichNum[4][9] = -1;
  StoichNum[4][10] = -1;
  StoichNum[4][21] = 1;
  StoichNum[4][24] = 1;
  StoichNum[4][25] = 1;
  StoichNum[5][0] = 1;
  StoichNum[5][1] = -1;
  StoichNum[5][3] = -1;
  StoichNum[5][13] = -1;
  StoichNum[5][18] = -1;
  StoichNum[5][21] = -1;
  StoichNum[5][22] = -1;
  StoichNum[6][0] = -1;
  StoichNum[6][1] = -1;
  StoichNum[6][2] = 1;
  StoichNum[6][3] = 1;
  StoichNum[6][5] = 1;
  StoichNum[6][8] = 0.1;
  StoichNum[6][9] = 0.14;
  StoichNum[6][10] = 0.18;
  StoichNum[6][11] = -1;
  StoichNum[6][12] = -1;
  StoichNum[6][14] = 1;
  StoichNum[6][20] = 2;
  StoichNum[6][22] = 1;
  StoichNum[6][23] = 1;
  StoichNum[7][12] = -1;
  StoichNum[7][15] = 1;
  StoichNum[7][17] = -1;
  StoichNum[7][19] = 1;
  StoichNum[7][24] = -1;
  StoichNum[8][4] = 2;
  StoichNum[8][11] = 1;
  StoichNum[8][12] = 1;
  StoichNum[8][13] = -1;
  StoichNum[8][14] = -2;
  StoichNum[8][15] = -2;
  StoichNum[8][16] = -1;
  StoichNum[8][17] = -1;
  StoichNum[8][18] = 1;
  StoichNum[8][23] = 1;
  StoichNum[8][24] = 1;
  StoichNum[9][11] = -1;
  StoichNum[9][12] = 1;
  StoichNum[9][13] = 1;
  StoichNum[9][16] = -1;
  StoichNum[9][17] = 1;
  StoichNum[9][18] = -1;
  StoichNum[9][19] = -2;
  StoichNum[9][23] = -1;
}

// End of CalcStoichNum function
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


